# Generated by Django 5.1.5 on 2025-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('resp', models.CharField(max_length=255)),
            ],
        ),
    ]
