# Generated by Django 5.1.5 on 2025-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ambientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutentores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
            ],
        ),
    ]
