# Generated by Django 5.1.5 on 2025-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gestores'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=255)),
                ('abert', models.DateTimeField()),
                ('fecha', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('patri', models.CharField(max_length=255)),
                ('ambi', models.CharField(max_length=255)),
                ('manu', models.CharField(max_length=255)),
                ('respo', models.CharField(max_length=255)),
                ('prio', models.CharField(max_length=255)),
            ],
        ),
    ]
