# Generated by Django 5.1.5 on 2025-04-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_odemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.TextField()),
                ('abert', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('prio', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=10)),
                ('ambi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambientes')),
                ('manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manutentores')),
                ('patri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patrimonios')),
                ('respo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gestores')),
            ],
        ),
        migrations.DeleteModel(
            name='OdemServico',
        ),
    ]
