# Generated by Django 5.1.5 on 2025-04-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordemservico_delete_odemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ambientes',
            name='ni',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='patri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patrimonio'),
        ),
        migrations.DeleteModel(
            name='Patrimonios',
        ),
    ]
