# Generated by Django 5.1.5 on 2025-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_patrimonio_remove_ambientes_ni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
