# Generated by Django 5.1.5 on 2025-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patrimonio_localizacao_alter_patrimonio_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientes',
            name='resp',
        ),
        migrations.AddField(
            model_name='ambientes',
            name='ni',
            field=models.CharField(default='LabTemp', max_length=255),
        ),
    ]
