# Generated by Django 5.1.5 on 2025-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ambientes_resp_ambientes_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='ni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
