# Generated by Django 5.1.5 on 2025-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_gestores_area_remove_gestores_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestores',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestores',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestores',
            name='ni',
            field=models.CharField(default='sn0000000', max_length=20),
            preserve_default=False,
        ),
    ]
